namespace: aerocast

images:
  api:
    # you will push: ghcr.io/mdgolammafuz/aerocast-api:latest
    repository: ghcr.io/mdgolammafuz/aerocast-api
    tag: latest
    pullPolicy: IfNotPresent

  worker:
    # you will push: ghcr.io/mdgolammafuz/aerocast-worker:latest
    repository: ghcr.io/mdgolammafuz/aerocast-worker
    tag: latest
    pullPolicy: IfNotPresent

  pushgateway:
    repository: prom/pushgateway
    tag: latest
    pullPolicy: IfNotPresent

  prometheus:
    repository: prom/prometheus
    tag: latest
    pullPolicy: IfNotPresent

  grafana:
    repository: grafana/grafana
    tag: latest
    pullPolicy: IfNotPresent

prometheus:
  scrapeInterval: 5s
  apiTarget: aerocast-api.aerocast.svc.cluster.local:8000
  pushgatewayTarget: aerocast-pushgateway.aerocast.svc.cluster.local:9091

grafana:
  adminUser: admin
  adminPassword: admin

trainer:
  # matches what we put in the Deployment so it doesn't retrain every 5s
  cooldownSeconds: 60
