global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'aerocast-fastapi'
    static_configs:
      # Uses the container name defined in docker-compose
      - targets: ['aerocast-api:8000']

  # --- NEW: Add the Go Queue here ---
  - job_name: 'aerocast-queue'
    static_configs:
      - targets: ['aerocast-queue:8081']
  # ----------------------------------

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['aerocast-pushgateway:9091']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']