apiVersion: v1
kind: ConfigMap
metadata:
  name: aerocast-prometheus-config
  namespace: {{ .Values.namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeInterval }}
    scrape_configs:
      - job_name: 'aerocast-fastapi'
        static_configs:
          - targets: ['{{ .Values.prometheus.apiTarget }}']

      - job_name: 'pushgateway'
        honor_labels: true
        static_configs:
          - targets: ['{{ .Values.prometheus.pushgatewayTarget }}']

      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
