apiVersion: apps/v1
kind: Deployment
metadata:
  name: aerocast-pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aerocast-pushgateway
  template:
    metadata:
      labels:
        app: aerocast-pushgateway
    spec:
      containers:
        - name: pushgateway
          image: prom/pushgateway:latest
          ports:
            - containerPort: 9091
