{{- if .Values.queue.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-queue
  namespace: {{ .Values.namespace }}
  labels:
    app: aerocast-queue
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.queue.service.port }}
      targetPort: {{ .Values.queue.service.port }}
      protocol: TCP
      name: http
  selector:
    app: aerocast-queue
{{- end }}