apiVersion: v1
kind: Service
metadata:
  name: aerocast-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: aerocast-core
  ports:
    - name: http
      port: 8000
      targetPort: 8000
