apiVersion: v1
kind: Service
metadata:
  name: aerocast-grafana
  labels:
    app: aerocast-grafana
spec:
  type: ClusterIP
  selector:
    app: aerocast-grafana
  ports:
    - name: http
      port: 3000
      targetPort: 3000

