apiVersion: v1
kind: Service
metadata:
  name: aerocast-prometheus
  labels:
    app: aerocast-prometheus
spec:
  type: ClusterIP
  selector:
    app: aerocast-prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090

